### ISSUE TITLE
Usergruppen funktionieren noch nicht richtig

### ISSUE THREAD

**Issue by LucRome** [LucRome/SWE_Semester4#39]
*siehe Branch `Admin-site-user-administration`*
- Die User werden mit den jeweiligen Forms erstellt
    - (wie in der View-Funktion vom Backend, aber eine View pro User)
- Für die jeweiligen Listen werden die User über `UserObj.objects.filter(...)` abgerufen
    - Bsp. Student: 
    ```
    students = Lecturer.objects.filter(
                matr_nr__contains=filter_form['matr_nr'].data,
                first_name__contains=filter_form['first_name'].data,
                last_name__contains=filter_form['last_name'].data,
                username__contains=filter_form['username'].data)
   ```
-> Es werden **alle** User angezeigt (auf die die Filter zutreffen), d.h. die Usergruppen werden nicht beachtet

- Öffnet man die SQLite-Datenbank mit dem VSCode Plugin ist da auch **kein** Eintrag in der Tabelle `users_user_groups`
- **Funktionieren die UserForms vielleicht noch nicht richtig?**

**Comment by codingHahn** [comment]
This should be addressed in the newest master. Could you rebase your branch onto the newest master?

**Comment by codingHahn** [comment]
Should be fixed for real now in master. Could you check?

PS: You may need to recreate your users for this to take effect

**Comment by LucRome** [comment]
While your pull request wass still open (2 or 3 days ago) I tested it by merging your changes in a temporary Test Branch, at that time it worked perfectly (I shortly said it during the meeting)

The frontend wants to meet tomorrow, to bring the admin site together and merge everything, I will try the changes out again when everything is merged. Hopefully it still works, then I will close this PR.
