### ISSUE TITLE
Datumseingabe verbessern

### ISSUE THREAD

**Issue by LucRome** [LucRome/SWE_Semester4#58]
- Ein Datum muss momentan im SQL-Format angegeben werden (also: `yyyy-mm-dd`)
- Besser geeignet wäre eine Eingabe in einem "gewohnten" Format (z.B. `dd.mm.yyyy`)

**Comment by LucRome** [comment]
Eine mögliche Herangehensweise wäre vielleicht eine eigene Klasse zu erstellen, welche von dem Datumsfeld erbt, aber die Darstellung des Datums umwandelt (d.h. fürs Frontend `dd.mm.yyyy` und fürs Backend `yyyy-mm-dd`

**Comment by phie73** [comment]
![image](https://user-images.githubusercontent.com/63649591/115894128-3600d180-a459-11eb-8bdc-9b78a9dc4724.png)
evtl wäre das auch eine herangehensweise, theoretisch ist es möglich in django solche widgets zu erstellen, wie das mit bootstrap zusammenpasst weiß ich jedoch nicht

**Comment by LucRome** [comment]
Sollte jetzt drinnen sein (wenn man bei dem InputFeld in Html `type="date"` angibt wird so ein Kalender automatisch hinzugefügt und auch die Anzeige entsprechend formatiert

**Comment by LucRome** [comment]
Sollte auf dem Admin-Site Branch jetzt jedenfalls so angezeigt werden
